import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from property.models import Amenity

amenities = [
    # Specified amenities
    'Free Wi-Fi',
    'Swimming Pool',
    'Gym',
    'Spa',
    'Restaurant',
    'Bar',
    'Room Service',
    'Parking',
    'Pet Friendly',
    'Conference Room',
    'Airport Shuttle',
    'Laundry Service',
    '24-hour Front Desk',
    'Non-Smoking Rooms',
    'Business Center',
    'Breakfast Included',
    'Air Conditioning',
    'Wheelchair Accessible',
    'Mini Bar',
    'Flat Screen TV',
    
    # Additional common amenities
    'Safe',
    'Coffee/Tea Maker',
    'Refrigerator',
    'Hair Dryer',
    'Iron/Ironing Board',
    'Balcony',
    'Ocean View',
    'City View',
    'Garden View',
    'Kitchenette',
    'Microwave',
    'Dishwasher',
    'Washing Machine',
    'Dryer',
    'Bathtub',
    'Shower',
    'Jacuzzi',
    'Hot Tub',
    'Sauna',
    'Steam Room',
    'Fitness Center',
    'Tennis Court',
    'Golf Course',
    'Beach Access',
    'Concierge Service',
    'Valet Parking',
    'Car Rental',
    'Tour Desk',
    'Currency Exchange',
    'ATM',
    'Gift Shop',
    'Library',
    'Game Room',
    'Playground',
    'Kids Club',
    'Babysitting Service',
    'Medical Services',
    'Pharmacy',
    'Shopping Mall',
    'Market',
    'Elevator',
    'Luggage Storage',
    'Lost and Found',
    'Security',
    'CCTV',
    'Fire Safety',
    'First Aid',
    'Daily Housekeeping',
    'Turndown Service',
    'Wake-up Service',
    'Newspaper',
    'Cable TV',
    'Satellite TV',
    'Pay-per-view',
    'Music System',
    'DVD Player',
    'Gaming Console',
    'High-speed Internet',
    'Ethernet Connection',
    'Phone',
    'Fax',
    'Photocopying',
    'Printing',
    'Meeting Rooms',
    'Event Facilities',
    'Wedding Services',
    'Catering',
    'Outdoor Pool',
    'Indoor Pool',
    'Pool Bar',
    'Poolside Service',
    'Pool Towels',
    'Sun Loungers',
    'Umbrellas',
    'Terrace',
    'Rooftop Bar',
    'BBQ Facilities',
    'Picnic Area',
    'Bicycle Rental',
    'Electric Vehicle Charging',
    'Smoking Area',
    'Chapel',
    'Mosque',
    'Temple',
    'Kosher Meals',
    'Halal Meals',
    'Vegetarian Options',
    'Gluten-free Options',
    'Room Dining',
    'In-room Breakfast',
    'Express Check-in',
    'Express Check-out',
    'Mobile Check-in',
    'Contactless Check-in',
    'Luggage Delivery',
    'Priority Reservations',
    'VIP Services',
    'Butler Service'
]

# Add amenities to database
for amenity_name in amenities:
    amenity, created = Amenity.objects.get_or_create(name=amenity_name)
    if created:
        print(f"Added amenity: {amenity_name}")
    else:
        print(f"Amenity already exists: {amenity_name}")

print(f"\nScript completed. Total amenities processed: {len(amenities)}")
