name: mobile
description: "Hotel booking mobile app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # HTTP requests
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Image caching
  cached_network_image: ^3.3.0
  
  # Rating display
  flutter_rating_bar: ^4.0.1
  
  # Date formatting
  intl: ^0.18.1
  
  # Map display
  google_maps_flutter: ^2.5.0
  
  # Image selection
  image_picker: ^1.0.5
  
  # OTP input
  pin_code_fields: ^8.0.1
  
  # Loading placeholders
  shimmer: ^3.0.0
  
  # UI components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true