"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta, datetime
import logging
from logging import Formatter, FileHandler
# Paths
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = Path.home() / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

# Custom file handler that uses date-based filenames
class DateBasedFileHandler(FileHandler):
    def __init__(self, log_dir, base_filename, *args, **kwargs):
        self.log_dir = Path(log_dir)
        self.base_filename = base_filename
        self.current_date = None
        self.current_file = None
        # Initialize with today's date
        self._update_filename()
        super().__init__(self.current_file, *args, **kwargs)
    
    def _update_filename(self):
        today = datetime.now().strftime("%Y-%m-%d")
        if today != self.current_date:
            self.current_date = today
            self.current_file = str(self.log_dir / f"{self.base_filename}-{today}.log")
    
    def emit(self, record):
        # Update filename if date changed
        self._update_filename()
        # If filename changed, close old file and open new one
        if self.baseFilename != self.current_file:
            self.close()
            self.baseFilename = self.current_file
            self.stream = self._open()
        super().emit(record)

# Custom formatter to include request type
class RequestFormatter(Formatter):
    def format(self, record):
        # Extract request method from record attributes (set via extra dict) or default to '-'
        request_method = getattr(record, 'request_method', '-')
        
        # Extract module name from logger name
        module_name = record.name.split('.')[-1] if '.' in record.name else record.name
        
        # Format: time - request type - module - logger message
        record.msg = f"{request_method} - {module_name} - {record.msg}"
        return super().format(record)

WEBSITE_URL = "http://localhost:8000"
# WEBSITE_URL = "http://192.168.18.16:8000"
# WEBSITE_URL = 'http://147.93.97.63/api'
# WEBSITE_URL = 'https://hsquareliving.com/api'
# WEBSITE_URL = 'http://10.0.2.2:8000/api'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ej5u9dnr4(h98f9dxl^f(9wrvhne$5pz^9@z_ph2p4m%%$e-^r"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "users",
    "property",
    "booking",
    "expenses",
    "offer",
    "stats",
    "blog",
    "whitenoise",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} - {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "request_formatter": {
            "()": RequestFormatter,
            "format": "{asctime} - {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{levelname}:{name}:{message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "backend_file": {
            "()": DateBasedFileHandler,
            "log_dir": LOG_DIR,
            "base_filename": "hsquare-backend-log",
            "formatter": "request_formatter",
            "encoding": "utf-8",
        },
        "request_file": {
            "()": DateBasedFileHandler,
            "log_dir": LOG_DIR,
            "base_filename": "hsquare-backend-requests",
            "formatter": "request_formatter",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["request_file", "console"],
            "level": "WARNING",
            "propagate": False,
        },
        "property": {
            "handlers": ["backend_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "users": {
            "handlers": ["backend_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "hsquare": {
            "handlers": ["backend_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:3001",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    "https://hsquareliving.in",
    "https://hsquareliving.in",
    "https://www.hsquareliving.in",
    "https://hsquareliving.com",
    "https://www.hsquareliving.com",
    "http://192.168.18.16:3000",
    "http://192.168.68.108:3000",
]

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)
