"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta, datetime
import logging
from logging import Formatter, FileHandler
from decouple import config, Csv
# Paths
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = Path(config('LOG_DIR', default=str(Path.home() / "logs")))
LOG_DIR = Path(LOG_DIR)
LOG_DIR.mkdir(parents=True, exist_ok=True)

# Custom file handler that uses date-based filenames
class DateBasedFileHandler(FileHandler):
    def __init__(self, log_dir, base_filename, *args, **kwargs):
        self.log_dir = Path(log_dir)
        self.base_filename = base_filename
        self.current_date = None
        self.current_file = None
        # Initialize with today's date
        self._update_filename()
        super().__init__(self.current_file, *args, **kwargs)
    
    def _update_filename(self):
        today = datetime.now().strftime("%Y-%m-%d")
        if today != self.current_date:
            self.current_date = today
            self.current_file = str(self.log_dir / f"{self.base_filename}-{today}.log")
    
    def emit(self, record):
        # Update filename if date changed
        self._update_filename()
        # If filename changed, close old file and open new one
        if self.baseFilename != self.current_file:
            self.close()
            self.baseFilename = self.current_file
            self.stream = self._open()
        super().emit(record)

# Custom formatter to include request type
class RequestFormatter(Formatter):
    def format(self, record):
        # Extract request method from record attributes (set via extra dict) or default to '-'
        request_method = getattr(record, 'request_method', '-')
        
        # Extract module name from logger name
        module_name = record.name.split('.')[-1] if '.' in record.name else record.name
        
        # Format: time - request type - module - logger message
        record.msg = f"{request_method} - {module_name} - {record.msg}"
        return super().format(record)

# Environment configuration (PROD or DEVELOP)
APP_ENV = config('APP_ENV', default='DEVELOP').upper()

# Domain configuration
DOMAIN = config('DOMAIN', default='localhost')
API_DOMAIN = config('API_DOMAIN', default=f'api.{DOMAIN}' if DOMAIN != 'localhost' else 'localhost:8000')

# Website URL configuration
if APP_ENV == 'PROD' and DOMAIN != 'localhost':
    # Production: Use API subdomain
    WEBSITE_URL = config('WEBSITE_URL', default=f'https://{API_DOMAIN}')
else:
    # Development: Use localhost
    WEBSITE_URL = config('WEBSITE_URL', default='http://localhost:8000')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY', default='django-insecure-ej5u9dnr4(h98f9dxl^f(9wrvhne$5pz^9@z_ph2p4m%%$e-^r')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=(APP_ENV != 'PROD'), cast=bool)

print("APP_ENV", APP_ENV)
# Allowed Hosts - include API subdomain
if APP_ENV == 'PROD' and DOMAIN != 'localhost':
    default_hosts = f'{API_DOMAIN},{DOMAIN},www.{DOMAIN}'
else:
    default_hosts = '*'
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=default_hosts, cast=Csv())
print("ALLOWED_HOSTS", ALLOWED_HOSTS)
ALLOWED_HOSTS.append('localhost')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "users",
    "property",
    "booking",
    "expenses",
    "offer",
    "stats",
    "blog",
    "whitenoise",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "backend.middleware.RateLimitMiddleware",  # Custom rate limiting
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "backend.middleware.SecurityHeadersMiddleware",  # Custom security headers
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')
DB_NAME = config('DB_NAME', default=str(BASE_DIR / "db.sqlite3"))
DB_USER = config('DB_USER', default='')
DB_PASSWORD = config('DB_PASSWORD', default='')
DB_HOST = config('DB_HOST', default='')
DB_PORT = config('DB_PORT', default='')
DB_OPTIONS = {}

# PostgreSQL SSL configuration
if DB_ENGINE == 'django.db.backends.postgresql':
    # For Aiven Cloud PostgreSQL, SSL is required
    # psycopg2 will automatically use SSL when connecting to servers that require it
    # We can explicitly set SSL mode if needed
    ssl_mode = config('DB_SSLMODE', default='require')
    
    # Set SSL connection parameters
    # Note: Django's PostgreSQL backend uses psycopg2 which handles SSL automatically
    # For explicit SSL configuration, we can use connection parameters
    if ssl_mode and ssl_mode != 'disable':
        # For Aiven Cloud, SSL is typically handled automatically
        # But we can set it explicitly if needed
        pass  # SSL will be handled by psycopg2 based on server requirements
    
    # If SSL certificate files are provided (for client certificate authentication)
    ssl_root_cert = config('DB_SSLROOTCERT', default='')
    if ssl_root_cert:
        DB_OPTIONS['sslcert'] = config('DB_SSLCERT', default='')
        DB_OPTIONS['sslkey'] = config('DB_SSLKEY', default='')
        DB_OPTIONS['sslrootcert'] = ssl_root_cert

DATABASES = {
    "default": {
        "ENGINE": DB_ENGINE,
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        "OPTIONS": DB_OPTIONS,
    }
}


# Cache
CACHES = {
    "default": {
        "BACKEND": config('CACHE_BACKEND', default='django_redis.cache.RedisCache'),
        "LOCATION": config('CACHE_LOCATION', default='redis://127.0.0.1:6379/1'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = config('LANGUAGE_CODE', default='en-us')

TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Throttling configuration for DDoS protection
    # Using custom throttle classes that exempt read-only GET endpoints
    "DEFAULT_THROTTLE_CLASSES": [
        "backend.throttling.ReadOnlyExemptAnonThrottle",
        "backend.throttling.ReadOnlyExemptThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # Throttling rates optimized for 5000+ DAU
        # Anonymous users: 1000 requests/hour (allows browsing, search, property views)
        "anon": config('THROTTLE_ANON_RATE', default='1000/hour' if APP_ENV == 'PROD' else '5000/hour'),
        # Authenticated users: 5000 requests/hour (allows normal app usage, dashboard refreshes, etc.)
        # With 5000 DAU, average user makes ~10-20 requests/hour during active use
        "user": config('THROTTLE_USER_RATE', default='5000/hour' if APP_ENV == 'PROD' else '20000/hour'),
        # Burst rate: 100 requests/minute (allows rapid interactions like form submissions, multiple API calls)
        "burst": config('THROTTLE_BURST_RATE', default='100/minute' if APP_ENV == 'PROD' else '500/minute'),
    },
    # Pagination to limit response sizes
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": config('API_PAGE_SIZE', default=50, cast=int),
    # Renderer and parser settings
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=config('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', default=5, cast=int)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=config('JWT_REFRESH_TOKEN_LIFETIME_DAYS', default=1, cast=int)),
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} - {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "request_formatter": {
            "()": RequestFormatter,
            "format": "{asctime} - {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{levelname}:{name}:{message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "backend_file": {
            "()": DateBasedFileHandler,
            "log_dir": LOG_DIR,
            "base_filename": config('LOG_BACKEND_FILENAME', default='hsquare-backend-log'),
            "formatter": "request_formatter",
            "encoding": "utf-8",
        },
        "request_file": {
            "()": DateBasedFileHandler,
            "log_dir": LOG_DIR,
            "base_filename": config('LOG_REQUEST_FILENAME', default='hsquare-backend-requests'),
            "formatter": "request_formatter",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["request_file", "console"],
            "level": "WARNING",
            "propagate": False,
        },
        "property": {
            "handlers": ["backend_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "users": {
            "handlers": ["backend_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "hsquare": {
            "handlers": ["backend_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# CORS Allowed Origins - allow main domain to access API subdomain
if APP_ENV == 'PROD' and DOMAIN != 'localhost':
    default_cors_origins = f'https://{DOMAIN},https://www.{DOMAIN}'
else:
    default_cors_origins = 'http://localhost:8000,http://localhost:3001,http://127.0.0.1:8080,http://127.0.0.1:3001,http://127.0.0.1:3000,http://localhost:3000,http://127.0.0.1:8000'

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default=default_cors_origins,
    cast=Csv()
)

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

# Security Settings based on environment
if APP_ENV == 'PROD':
    # Production Security Settings
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
    SECURE_CONTENT_TYPE_NOSNIFF = config('SECURE_CONTENT_TYPE_NOSNIFF', default=True, cast=bool)
    SECURE_BROWSER_XSS_FILTER = config('SECURE_BROWSER_XSS_FILTER', default=True, cast=bool)
    X_FRAME_OPTIONS = config('X_FRAME_OPTIONS', default='DENY')
    SECURE_REFERRER_POLICY = config('SECURE_REFERRER_POLICY', default='strict-origin-when-cross-origin')
    USE_TZ = True
else:
    # Development Security Settings (more relaxed)
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'

# Additional Security Headers
SECURE_PROXY_SSL_HEADER = config('SECURE_PROXY_SSL_HEADER', default=None)
if SECURE_PROXY_SSL_HEADER and SECURE_PROXY_SSL_HEADER.strip():
    # Format: HTTP_HEADER_NAME,HEADER_VALUE
    parts = SECURE_PROXY_SSL_HEADER.split(',')
    if len(parts) == 2:
        SECURE_PROXY_SSL_HEADER = (parts[0].strip(), parts[1].strip())
    else:
        SECURE_PROXY_SSL_HEADER = None

# CSRF Settings
CSRF_COOKIE_HTTPONLY = config('CSRF_COOKIE_HTTPONLY', default=True, cast=bool)
CSRF_COOKIE_SAMESITE = config('CSRF_COOKIE_SAMESITE', default='Lax' if APP_ENV == 'PROD' else 'Lax')

# CSRF Trusted Origins - include API subdomain and main domain
if APP_ENV == 'PROD' and DOMAIN != 'localhost':
    default_csrf_origins = f'https://{API_DOMAIN},https://{DOMAIN},https://www.{DOMAIN}'
else:
    default_csrf_origins = 'http://localhost:8000,http://127.0.0.1:8000'

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default=default_csrf_origins, cast=Csv())

# Session Security
SESSION_COOKIE_HTTPONLY = config('SESSION_COOKIE_HTTPONLY', default=True, cast=bool)
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax' if APP_ENV == 'PROD' else 'Lax')
SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', default=86400 if APP_ENV == 'PROD' else 86400, cast=int)  # 24 hours

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = config('FILE_UPLOAD_MAX_MEMORY_SIZE', default=10485760 if APP_ENV == 'PROD' else 52428800, cast=int)  # 10MB prod, 50MB dev
DATA_UPLOAD_MAX_MEMORY_SIZE = config('DATA_UPLOAD_MAX_MEMORY_SIZE', default=10485760 if APP_ENV == 'PROD' else 52428800, cast=int)
DATA_UPLOAD_MAX_NUMBER_FIELDS = config('DATA_UPLOAD_MAX_NUMBER_FIELDS', default=1000 if APP_ENV == 'PROD' else 10000, cast=int)

# Request Timeout (prevent slowloris attacks)
if APP_ENV == 'PROD':
    # Shorter timeout in production
    DATA_UPLOAD_MAX_MEMORY_SIZE = min(DATA_UPLOAD_MAX_MEMORY_SIZE, 10485760)  # 10MB max

# Logging for security events
if APP_ENV == 'PROD':
    LOGGING['loggers']['django.security'] = {
        'handlers': ['backend_file', 'console'],
        'level': 'WARNING',
        'propagate': False,
    }
