# Generated by Django 5.1.5 on 2025-02-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_amount',
            new_name='discount_percentage',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='offer_status',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_image',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='offerimage',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.offer'),
        ),
    ]
