# Generated by Django 4.2.25 on 2025-10-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_description',
        ),
    ]
