# Generated by Django 5.1.5 on 2025-02-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_images_propertyimage_property_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
    ]
