# Generated by Django 5.1.5 on 2025-02-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_propertyimage_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King'), ('twin', 'Twin'), ('double_twin', 'Double Twin'), ('bunk', 'Bunk'), ('sofa', 'Sofa'), ('sofa_bed', 'Sofa Bed')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='private_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='sercurity_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
    ]
