# Generated by Django 5.1.5 on 2025-02-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_city_country_state_property_city_property_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number_of_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='used_number_of_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
