# Generated by Django 5.1.5 on 2025-02-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_room_number_of_rooms_room_used_number_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
