# Generated by Django 5.1.5 on 2025-02-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='left_number_of_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
