# Generated by Django 5.1.5 on 2025-02-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_room_left_number_of_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='daily_rate',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='sercurity_deposit',
            new_name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='room',
            name='discount',
        ),
        migrations.AddField(
            model_name='room',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
