# Generated by Django 5.1.5 on 2025-03-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='property.property'),
        ),
    ]
