# Generated by Django 5.1.5 on 2025-06-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_userproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='yearly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
