# Generated by Django 5.1.5 on 2025-10-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_room_yearly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='category',
            field=models.CharField(
                choices=[
                    ('room', 'Room'),
                    ('bathroom', 'Bathroom'),
                    ('waiting_room', 'Waiting Room'),
                    ('facade', 'Facade'),
                    ('parking', 'Parking'),
                    ('lobby', 'Lobby'),
                    ('dining', 'Dining'),
                    ('exterior', 'Exterior'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=20
            ),
        ),
    ]

