# Generated by Django 4.2.24 on 2025-10-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_add_room_gender_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='gender_type',
        ),
        migrations.AddField(
            model_name='property',
            name='gender_type',
            field=models.CharField(blank=True, choices=[('unisex', 'Unisex'), ('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
