# Generated by Django 4.2.24 on 2025-11-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_imagecategory_model'),
        ('property', '0024_image_categories_dynamic'),
    ]

    operations = [
    ]
