# Generated by Django 4.2.25 on 2025-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_merge_20251109_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='nearby_places',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
