# Generated by Django 4.2.25 on 2025-11-09 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def forwards_migrate_nearby_places(apps, schema_editor):
    Property = apps.get_model('property', 'Property')
    NearbyPlace = apps.get_model('property', 'NearbyPlace')

    for property_obj in Property.objects.all():
        raw_places = getattr(property_obj, 'nearby_places', None)
        if not raw_places:
            continue

        if isinstance(raw_places, dict):
            if 'items' in raw_places and isinstance(raw_places['items'], list):
                entries = raw_places['items']
            else:
                entries = list(raw_places.values())
        elif isinstance(raw_places, list):
            entries = raw_places
        else:
            entries = []

        if not isinstance(entries, list):
            continue

        for index, entry in enumerate(entries):
            if not isinstance(entry, dict):
                continue
            name = str(entry.get('name', '') or '').strip()
            category = str(entry.get('category', '') or '').strip()
            distance = str(entry.get('distance', '') or '').strip()

            if not name or not category or not distance:
                continue

            NearbyPlace.objects.create(
                property=property_obj,
                name=name,
                category=category,
                distance=distance,
                sort_order=index,
            )


def backwards_migrate_nearby_places(apps, schema_editor):
    Property = apps.get_model('property', 'Property')
    NearbyPlace = apps.get_model('property', 'NearbyPlace')

    for property_obj in Property.objects.all():
        places = NearbyPlace.objects.filter(property=property_obj).order_by('sort_order', 'name')
        property_obj.nearby_places = [
            {
                'name': place.name,
                'category': place.category,
                'distance': place.distance,
            }
            for place in places
        ]
        property_obj.save(update_fields=['nearby_places'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_property_nearby_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('distance', models.CharField(help_text="Distance in a human readable format e.g. '1.5 km'", max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_nearby_places', to='property.property')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(
            forwards_migrate_nearby_places,
            backwards_migrate_nearby_places,
        ),
        migrations.RemoveField(
            model_name='property',
            name='nearby_places',
        ),
        migrations.AlterField(
            model_name='nearbyplace',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='property.property'),
        ),
    ]
