# Generated by Django 4.2.25 on 2025-11-10 07:49

from django.db import migrations, models
import django.utils.timezone


def seed_site_pages(apps, schema_editor):
    SitePage = apps.get_model('property', 'SitePage')
    HsPermission = apps.get_model('users', 'HsPermission')

    HsPermission.objects.get_or_create(
        name='admin:pages:manage',
        defaults={'description': 'Manage public marketing pages (events, team, partner).'}
    )

    default_pages = [
        {
            "slug": "events",
            "title": "Events",
            "hero_title": "Host remarkable events with HSquare Living",
            "hero_description": "Transform your next gathering with inspiring venues, warm hospitality, and end-to-end event management across our hotels and hostels.",
            "sections": [
                {
                    "heading": "Tailored venues for every occasion",
                    "body": "From corporate offsites to intimate celebrations, our curated portfolio of hotels and hostels across India feature flexible venues, modern amenities, and hospitality teams that execute every detail flawlessly.",
                },
                {
                    "heading": "Dedicated event specialists",
                    "body": "Our on-ground experts assist with planning, vendor coordination, décor, catering, and guest logistics so you can focus on creating unforgettable moments.",
                },
                {
                    "heading": "Seamless guest experiences",
                    "body": "Ensure your attendees enjoy comfortable stays, curated itineraries, and local experiences with our concierge support and city partners.",
                },
            ],
        },
        {
            "slug": "team",
            "title": "Team",
            "hero_title": "Meet the people behind HSquare Living",
            "hero_description": "A collective of hospitality experts, designers, and storytellers working together to craft unforgettable stays across India.",
            "sections": [
                {
                    "heading": "Built by hospitality specialists",
                    "body": "Led by seasoned professionals across operations, design, finance, and technology, our leadership team blends global experience with a deep understanding of India’s hospitality landscape.",
                },
                {
                    "heading": "Powered by passionate hosts",
                    "body": "Across every property, our on-ground teams go above and beyond to make sure every guest feels heard, supported, and celebrated throughout their stay.",
                },
                {
                    "heading": "Driven by a shared purpose",
                    "body": "We are united by a single mission—to reimagine hotels and hostels for modern travellers through thoughtful design, meaningful service, and memorable experiences.",
                },
            ],
        },
        {
            "slug": "partner-with-us",
            "title": "Partner With Us",
            "hero_title": "Grow with HSquare Living",
            "hero_description": "Collaborate with us to elevate your property, unlock steady revenue, and deliver experiences that keep guests coming back.",
            "sections": [
                {
                    "heading": "Unlock better occupancy and revenue",
                    "body": "Leverage HSquare Living’s distribution, brand standards, and revenue management expertise to attract premium travellers 365 days a year.",
                    "items": [
                        {
                            "title": "Dedicated account management",
                            "description": "Work with specialists who understand your property goals and help optimise pricing, positioning, and guest satisfaction.",
                        },
                        {
                            "title": "Centralised operations",
                            "description": "From housekeeping to guest communication and technology integration, we streamline operations so you can focus on growth.",
                        },
                    ],
                },
                {
                    "heading": "Become part of a trusted hospitality network",
                    "body": "Join a growing ecosystem of hotels, hostels, and experiential stays that travellers rely on for consistency, comfort, and curated design.",
                },
                {
                    "heading": "Let’s co-create unforgettable stays",
                    "body": "Partner with us to transform your property into a high-performing destination with signature HSquare Living service standards.",
                },
            ],
        },
    ]

    for page in default_pages:
        SitePage.objects.update_or_create(
            slug=page["slug"],
            defaults={
                "title": page["title"],
                "hero_title": page["hero_title"],
                "hero_description": page["hero_description"],
                "sections": page["sections"],
                "extra": {},
                "is_active": True,
            },
        )


def unseed_site_pages(apps, schema_editor):
    SitePage = apps.get_model('property', 'SitePage')
    HsPermission = apps.get_model('users', 'HsPermission')

    for slug in ['events', 'team', 'partner-with-us']:
        SitePage.objects.filter(slug=slug).delete()

    HsPermission.objects.filter(name='admin:pages:manage').delete()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_remove_property_nearby_places_nearbyplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_description', models.TextField(blank=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.RunPython(seed_site_pages, unseed_site_pages),
    ]
