# Generated by Django 5.1.5 on 2025-02-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status_bookingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('walkin', 'Walkin'), ('online', 'Online'), ('makemytrip', 'Makemytrip'), ('tripadvisor', 'Tripadvisor'), ('expedia', 'Expedia'), ('agoda', 'Agoda'), ('bookingcom', 'Booking.com'), ('airbnb', 'Airbnb'), ('other', 'Other')], default='walkin', max_length=20),
        ),
    ]
