# Generated by Django 5.1.5 on 2025-04-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_room_types',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
