# Generated by Django 5.1.5 on 2025-04-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_booking_room_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
