# Generated by Django 5.1.5 on 2025-04-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_review_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
