# Generated by Django 5.1.5 on 2025-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_is_review_created_booking_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='offer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
