# Generated by Django 4.2.24 on 2025-10-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_hostelvisit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hostelvisit',
            new_name='booking_hos_visit_d_145790_idx',
            old_name='booking_hos_visit_d_7b9c3e_idx',
        ),
        migrations.RenameIndex(
            model_name='hostelvisit',
            new_name='booking_hos_status_0410b5_idx',
            old_name='booking_hos_status_8f4d2a_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20),
        ),
    ]
