# Generated by Django 4.2.24 on 2025-10-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userdocument'),
        ('booking', '0013_rename_booking_hos_visit_d_7b9c3e_idx_booking_hos_visit_d_145790_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelvisit',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hostelvisit',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hostelvisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hsuser'),
        ),
    ]
