# Generated by Django 5.1.5 on 2025-01-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_hspermission_users_alter_hspermission_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsuser',
            name='name',
            field=models.CharField(blank=True, default='user', max_length=255, null=True),
        ),
    ]
