# Generated by Django 5.1.5 on 2025-02-03 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_hsuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhspermission',
            name='permission',
        ),
        migrations.AlterField(
            model_name='userhspermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hsuser'),
        ),
        migrations.CreateModel(
            name='HsPermissionGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('permissions', models.ManyToManyField(related_name='permission_groups', to='users.hspermission')),
            ],
        ),
        migrations.AddField(
            model_name='userhspermission',
            name='permission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hspermissiongroup'),
        ),
    ]
