# Generated by Django 5.1.5 on 2025-02-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_hspermission_created_at_hspermissiongroup_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hspermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hspermissiongroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userhspermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
