# Generated by Django 5.1.5 on 2025-04-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_hspermission_is_active_hspermissiongroup_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsuser',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee')], default='admin', max_length=20),
        ),
    ]
