# Generated by Django 4.2.25 on 2025-11-20 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hsuser')),
            ],
            options={
                'db_table': 'refresh_tokens',
                'indexes': [models.Index(fields=['token'], name='refresh_tok_token_e21bac_idx'), models.Index(fields=['user', 'is_active'], name='refresh_tok_user_id_f5e249_idx')],
            },
        ),
    ]
