from django.urls import path
from . import views

urlpatterns = [
    path('amenities/', views.amenity_list, name='amenity-list'),
    path('amenities/<int:pk>/', views.amenity_detail, name='amenity-detail'),
    path('rules/', views.rule_list, name='rule-list'),
    path('rules/<int:pk>/', views.rule_detail, name='rule-detail'),
    path('documentations/', views.documentation_list, name='documentation-list'),
    path('documentations/<int:pk>/', views.documentation_detail, name='documentation-detail'),
    path('image-categories/', views.image_category_list, name='image-category-list'),
    path('image-categories/<int:pk>/', views.image_category_detail, name='image-category-detail'),
    path('rooms/', views.room_list, name='room-list'),
    path('rooms/<int:pk>/', views.room_detail, name='room-detail'),
    path('properties/', views.property_list, name='property-list'),
    path('properties/<int:pk>/', views.property_detail, name='property-detail'),
    path('reviews/', views.review_list, name='review-list'),
    path('reviews/top/', views.top_reviews_by_property_type, name='top-reviews-by-property-type'),
    path('reviews/<int:pk>/', views.review_detail, name='review-detail'),
    path('replies/', views.reply_list, name='reply-list'),
    path('replies/<int:pk>/', views.reply_detail, name='reply-detail'),
    path('images/upload/', views.image_upload, name='image-upload'),
    path('images/<int:pk>/', views.image_detail, name='image-detail'),
    path('room/images/upload/', views.room_image_upload, name='room-image-upload'),
    path('search/<str:location>/', views.search_properties_by_location, name='search-properties-by-location'),
    path('public/search/', views.public_search_properties, name='public-search-properties'),
    path('city/', views.list_cities, name='list-cities'),
    path('country/', views.list_countries, name='list-countries'),
    path('state/', views.list_states, name='list-states'),
    path('areas/<str:city_name>/', views.unique_areas_by_city, name='unique-areas-by-city'),
    path('toggle-favourite/', views.add_favorite_property, name='add-favorite-property'),
    path('favorite-properties/', views.get_favorite_properties, name='get-favorite-properties'),
    path('site-pages/', views.site_page_list, name='site-page-list'),
    path('site-pages/<slug:slug>/', views.site_page_detail, name='site-page-detail'),
    path('site-pages/upload-image/', views.site_page_upload_image, name='site-page-upload-image'),
    path('settings/', views.settings_list, name='settings-list'),
    path('settings/<str:key>/', views.settings_detail, name='settings-detail'),
    path('reviews/create/', views.create_review, name='create_review'),
    path('all-properties/', views.get_all_properties, name='get-all-properties'),
    path('user-properties/', views.get_user_properties, name='get-user-properties'),
    path('add-properties-to-user/', views.add_properties_to_user, name='add-properties-to-user'),
]

